version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: listifydb
      POSTGRES_USER: listify_user
      POSTGRES_PASSWORD: listify_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: